In [1]:
import tensorflow as tf 

In [2]:
print(tf.__version__)

2.10.0


In [6]:
x = tf.constant(3)
print(x)

tf.Tensor(3, shape=(), dtype=int32)


In [10]:
x = tf.constant(4.5)
print(x)

tf.Tensor(4.5, shape=(), dtype=float32)


In [17]:
x = tf.constant(3,shape= (1,1))
print(x)

tf.Tensor([[3]], shape=(1, 1), dtype=int32)


In [18]:
x = tf.constant(3,shape= (1,2))
print(x)

tf.Tensor([[3 3]], shape=(1, 2), dtype=int32)


In [20]:
x = tf.constant(3,shape= (3,1))
print(x)

tf.Tensor(
[[3]
 [3]
 [3]], shape=(3, 1), dtype=int32)


In [21]:
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [26]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [28]:
x = tf.zeros((3,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [30]:
x = tf.eye(3)
print(x)
# identity matrix

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [35]:
x = tf.random.normal((3,3) , mean=0 , stddev=1)
print(x)

tf.Tensor(
[[-0.6237902  -0.22428948 -0.47711465]
 [-0.6379997   2.1734731   0.3349781 ]
 [-1.4145983  -2.1133761  -0.32859236]], shape=(3, 3), dtype=float32)


In [38]:
x = tf.random.uniform((1,3) , minval=0 , maxval=1)
print(x)

tf.Tensor([[0.11798346 0.8096342  0.4471841 ]], shape=(1, 3), dtype=float32)


In [39]:
x = tf.range(4)
print(x)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)


In [40]:
x = tf.range(start=1 , limit=15 , delta=2)
print(x)

tf.Tensor([ 1  3  5  7  9 11 13], shape=(7,), dtype=int32)


In [43]:
x = tf.cast(x ,dtype=tf.float32)
print(x)

tf.Tensor([ 1.  3.  5.  7.  9. 11. 13.], shape=(7,), dtype=float32)


In [44]:
z = tf.constant([1,2,3])
t = tf.constant([9,8,7])

In [47]:
a = tf.add(z,t)
print(a)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [50]:
b = tf.subtract(t,z)
print(b)

tf.Tensor([8 6 4], shape=(3,), dtype=int32)


In [51]:
c = tf.multiply(t,z)
print(c)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [53]:
d = tf.divide(t,z)
print(d)

tf.Tensor([9.         4.         2.33333333], shape=(3,), dtype=float64)


In [63]:
x = tf.random.normal((3,2))
y = tf.random.normal((2,4))
z = tf.matmul(x,y)
# we can use "z = x @ y" instead of "matmul(x,y)"

In [64]:
print(z)

tf.Tensor(
[[ 0.48640004 -0.5002841  -0.33576927  0.31591797]
 [-0.5005599  -0.15206058 -0.6348525  -0.03295704]
 [-0.12924321  0.26099026  0.27747145 -0.14004306]], shape=(3, 4), dtype=float32)


In [70]:
x = tf.range(9)
print(x)
x = tf.reshape(x , ((3,3)))
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [71]:
x = tf.transpose(x ,perm=[1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
